image: gitlab-registry.cern.ch/computersecurity/security-services-code-checking:latest

#
# Job types
#
types:
    - build
    - test

job1:
  type: build
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  before_script: 
  - cd ..
  - tar czf repo.tar.gz ltau_analyzers
  - set +e && source /cvmfs/cms.cern.ch/cmsset_default.sh; set -e
  - export SCRAM_ARCH=slc6_amd64_gcc630
  - scramv1 project CMSSW CMSSW_10_4_0
  - cd CMSSW_10_4_0/src
  - mv ../../repo.tar.gz .
  - tar xzf repo.tar.gz
  - eval `scramv1 runtime -sh`
  - cd ${CMSSW_BASE}/src
  - git clone https://github.com/cms-tau-pog/TauIDSFs TauPOG/TauIDSFs
  - cd ${CMSSW_BASE}/src
  - scram b
  - cd ltau_analyzers
  script:
  - echo "start"
  - echo `ls`
  - echo `ls $CMSSW_BASE/lib/$SCRAM_ARCH/`
  - ./build plugins/et_analyzer2016.cc test
  - ./build plugins/et_analyzer2017.cc test
  - ./build plugins/et_analyzer2018.cc test
  - ./build plugins/mt_analyzer2016.cc test
  - ./build plugins/mt_analyzer2017.cc test
  - ./build plugins/mt_analyzer2018.cc test

#
# Job: run CppLint
#
run_cpplint:
    type: test
    script:
        - cpplint --linelength=1000 --exclude=./plugins/et_analyzer2016_AC.cc --exclude=./plugins/mt_templateMaker.cc --exclude=./plugins/tt_analyzer.cc ./plugins/*
  
